### ISSUE TITLE
upgrade Calligraphy for viewpump:2.0.0

### ISSUE THREAD

**Issue by Ali72** [InflationX/Calligraphy#19]
please upgrade Calligraphy for match with
io.github.inflationx:viewpump:2.0.0

**Comment by jbarr21** [comment]
I don't believe we've broken any APIs. Could you please be more specific with the issue that you are encountering?

**Comment by jameswald** [comment]
One issue is that Calligraphy can't access ViewPump's ReflectionUtils:

<img width="496" alt="Screen Shot 2019-04-09 at 4 44 56 PM" src="https://user-images.githubusercontent.com/875535/55842089-de4bd380-5ae6-11e9-802f-3ca1606d0901.png">

This seems to be an issue with ViewPump 1.0.0 too, though.

**Comment by jbarr21** [comment]
@jameswald ah, yes, looks like https://github.com/InflationX/ViewPump/pull/25 made this internal. seems reasonable to duplicate instead of depending on internals of another lib

**Comment by ZacSweers** [comment]
I'll PR a fix later today if someone else doesn't get around to it first

**Comment by flo5324** [comment]
Proguard also raise warning on this ReflectionUtils class
I imagine that when this class will be duplicated in Calligraphy, this will no longer appear ?

`Warning: io.github.inflationx.calligraphy3.Calligraphy: can't find referenced class io.github.inflationx.viewpump.ReflectionUtils`
`Warning: io.github.inflationx.calligraphy3.Calligraphy: can't find referenced class io.github.inflationx.viewpump.ReflectionUtils`
`Warning: io.github.inflationx.calligraphy3.Calligraphy: can't find referenced class io.github.inflationx.viewpump.ReflectionUtils`

Calligraphy 3.3.0
ViewPump 2.0.1
