### ISSUE TITLE
setFontAtrrId(R.attr.fontPath) fontPath not resolved

### ISSUE THREAD

**Issue by Gkundu1** [InflationX/Calligraphy#21]
CalligraphyConfig.initDefault(new CalligraphyConfig.Builder()
                                        .setDefaultFontPath("fonts/" + getString(R.string.filename_default_font_narrow))
                                        .setFontAttrId(R.attr.fontPath)
                                        .build());
The R.attr.fontPath not resolve.

Library using implementation 'uk.co.chrisjenx:calligraphy:2.3.0'
Support library: versions = [supportLib: "27.1.1"]
Gradle build tool version : classpath 'com.android.tools.build:gradle:3.1.4'

**Comment by jbarr21** [comment]
this is a fork of that lib under the io.github.inflationx.calligraphy3 namespace. for issues before 3.0, please create an issue on that repo https://github.com/chrisjenx/Calligraphy
