### ISSUE TITLE
Unresolved reference: fontPath

### ISSUE THREAD

**Issue by MahdiFarzami** [InflationX/Calligraphy#27]
Hi , i get this error  --> The R.attr.fontPath not resolve. for this line --> setFontAttrId(R.attr.fontPath) 

ViewPump.init(
ViewPump.builder()
.addInterceptor(
CalligraphyInterceptor(
CalligraphyConfig.Builder()
.setDefaultFontPath(FONTS_ASSET_PATH + FONT_NAME_REGULAR)
.setFontAttrId(R.attr.fontPath)
.build()
)
)
.build()

Library using implementation 'io.github.inflationx:calligraphy3:3.1.1'

**Comment by farzadfarazmand** [comment]
@mahdi68  It's ok in 3.1.0 , you can use that one

**Comment by erlangparasu** [comment]
hello sir.. you dont need to call `.setFontAttrId(R.attr.fontPath)` :)
