### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver

### ISSUE THREAD

**Issue by Gkundu1** [InflationX/Calligraphy#42]
> Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.ClassCastException: io.github.inflationx.viewpump.ViewPumpContextWrapper cannot be cast to android.app.ContextImpl

The above message appears and closes the application when the application running in the device for the first time.
Keep appearing once updated the code with the line under my custom application class

```
override fun attachBaseContext(base: Context?) {
        super.attachBaseContext(ViewPumpContextWrapper.wrap(base!!))
    }
```
As per the documentation its mandatory to implement the above mention code to load or inject the custom font.

**Comment by erleizh** [comment]
https://github.com/chrisjenx/Calligraphy/issues/357

**Comment by devabir93** [comment]
any help please ?

**Comment by chrisjenx** [comment]
Did you `attachBaseContext` to the `Application` class instead of `Activity` by chance? you override the Activity not the Application class, double check that, and if there is still an issue please reopen.
