### ISSUE TITLE
Calligraphy with CompileSDKVersion = 29

### ISSUE THREAD

**Issue by hantrungkien** [InflationX/Calligraphy#48]
Thanks for nice library but have we had a plan for fix this?
https://stackoverflow.com/a/57232072/4411879

**Comment by rayworks** [comment]
> implementation 'io.github.inflationx:calligraphy3:3.1.1'
implementation 'io.github.inflationx:viewpump:2.0.3'

Upgrading the libraries (to above version) works for me.

**Comment by mobileapppaul** [comment]
@rayworks i doesn't for me can you share more info of how you go it working ?

@hantrungkien  did you get it to work ?

**Comment by rayworks** [comment]
@mobileapppaul  You could follow the steps for upgrade which mentioned in here(https://stackoverflow.com/a/57232072/4411879).
If it still doesn't work, you may attach the related error log.

**Comment by mobileapppaul** [comment]
thanks @rayworks yes I have followed all the steps and still getting the error. 

I posted the error log [here](https://github.com/InflationX/Calligraphy/issues/53).

We have removed this library now.

**Comment by chrisjenx** [comment]
We fixed this pretty quickly, make sure you are using ViewPump 2.0.3: https://github.com/InflationX/ViewPump/blob/master/CHANGELOG.md#version-203-2019-06-07
