### ISSUE TITLE
Apply custom font at run-time downloaded from WebServer.

### ISSUE THREAD

**Issue by neopraveen** [InflationX/Calligraphy#49]
Is it possible to download a custom font file from my webserver and apply it at run-time.

**Comment by ChannVincent** [comment]
Hi, I would like to do the same thing.
Apply fonts at run-time, downloaded from webserver.
Is there any news here?

**Comment by neopraveen** [comment]
Finally I handled that with my custom views. There is no way to achieve this via Calligraphy. I suggest you to don't waste your precious time here.

**Comment by willis-tagheuer** [comment]
> Finally I handled that with my custom views. There is no way to achieve this via Calligraphy. I suggest you to don't waste your precious time here.

Hi ! Would you be able to share your solution to the community ? That would be great ! Thank you
