### ISSUE TITLE
ViewPumpContextWrapper is final

### ISSUE THREAD

**Issue by battbot-snappy** [InflationX/Calligraphy#55]
I moved from v2 to v3 today and found that the new context wrapper is a final class. I was extending the old context wrapper to allow for locale changing in my app but now i cannot fulfill my need to allow for custom fonts + locale changes together. Is there any particular reason ViewPumpContextWrapper has to be final?

**Comment by chrisjenx** [comment]
Create a Locale Interceptor, Calligraphy uses an interceptor to do the font manipulation, just do the same for Locale
