### ISSUE TITLE
fontPath attribute not working with DialogFragment

### ISSUE THREAD

**Issue by rahulr4** [InflationX/Calligraphy#59]
Hi,
fontPath attribute is not working with any type of DialogFragment.
I am using BottomSheetDialogFragment and in its layout i am defining the fontPath attribute just like i do for normal activities and fragments but the font is not working.

My configuration is correct because i am using it across the app and it works. It only does not work for Dialog Fragments.
Please help to resolve this

**Comment by OhJeongGyu** [comment]
Hello, my app has same issues. Only BottomSheetDialog shows not applied font
